### ISSUE TITLE
如何防止指纹检测

### ISSUE THREAD

**Issue by TroyMitchell911** [g1879/DrissionPage#300]
如何修改每一个ChromiumPage都为不同的指纹?

**Comment by AnthraX1** [comment]
https://github.com/brave/brave-browser

The easiest way is to use Brave instead of Chromium. Or you could patch HTMLCanvasElement.toDataURL() and CanvasRendering2dContext.getImageData, HTMLCanvasElement.toBlob,  OffscreenCanvas.convertToBlob by overriding prototype methods by injecting js before page is loaded. For example

```
var toDataURL = HTMLCanvasElement.prototype.toDataURL;
HTMLCanvasElement.prototype.toDataURL = function(type, encoderOptions) {
  var uri = toDataURL.call(this, type, encoderOptions);
  console.log(uri);
  return uri;
}

var canvas = document.createElement('canvas');
canvas.toDataURL()
```

**Comment by TroyMitchell911** [comment]
> https://github.com/brave/brave-browser
> 
> 最简单的方法是使用 Brave 而不是 Chromium。或者，您可以通过在页面加载前注入 js 来覆盖原型方法来修补 HTMLCanvasElement.toDataURL() 和 CanvasRendering2dContext.getImageData、HTMLCanvasElement.toBlob、OffscreenCanvas.convertToBlob。例如
> 
> ```
> var toDataURL = HTMLCanvasElement.prototype.toDataURL;
> HTMLCanvasElement.prototype.toDataURL = function(type, encoderOptions) {
>   var uri = toDataURL.call(this, type, encoderOptions);
>   console.log(uri);
>   return uri;
> }
> 
> var canvas = document.createElement('canvas');
> canvas.toDataURL()
> ```

Thanks for you response.
I have tried to use plug to resolve this problem.It is `FingerprintDefender`
